Description: "AE"

DATA:
  in_dir: ../data/input/Annot
  rna_dir: ../data/input/RNAss
  chr_dir: ../data/input/Chromatin
  out_dir: ../output
  w2v_model: ../data/word2vec/dna2vec.w2v
  
  cas9_wt_kim: Cas9_wt_kim #.tsv
  cas9_wt_wang: Cas9_wt_wang #.tsv
  cas9_wt_xiang: Cas9_wt_xiang #.tsv
  cas9_hf_wang: Cas9_HF1_wang #.tsv
  cas9_esp_wang: Cas9_esp_wang #.tsv
  cas12a_wt_kim: Cas12a_wt_kim #.tsv

MODEL:
  seed: 1234
  kmer: 5
  batch: 512
  epoch: 10
  earlystop: 10