Description: "AE"

DATA:
  in_dir: ../data/Raw_data
  rna_dir: ../data/input/RNAss
  chr_dir: ../data/input/Chromatin
  out_dir: ../output
  w2v_model: ../data/word2vec/dna2vec.w2v
  
  cas9_kim: Kim-Cas9/aax9249_table_s1.xlsx
  cas9_wang: Wang/41467_2019_12281_MOESM3_ESM.xlsx
  cas9_xiang: Xiang/41467_2021_23576_MOESM4_ESM.xlsx
  cas12a_kim: Kim-Cas12a/41587_2018_BFnbt4061_MOESM39_ESM.xlsx

MODEL:
  kfold: 5
  seed: 1234
  kmer: 5
  stride: 1
  batch: 256
  epoch: 500
  earlystop: 30
  seqlen: 30
  embd: 1